server:
  address: localhost
  port: ${PORT:0}
  
eureka:
  instance:
    hostname: ${server.address}
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ 
