#########################################################
# Classpath properties:
# 
# EUREKA.INSTANCE.HTTP.PROTOCOL - default(http) , could be given as https
# EUREKA.INSTANCE.ADDRESS - default(localhost)
# EUREKA.INSTANCE.PORT - default(4340)
##########################################################  
eureka:
  instance:
    hostname: ${EUREKA.INSTANCE.ADDRESS:localhost}
    port: ${PORT:4340}
    http-protocol: ${EUREKA.INSTANCE.HTTP.PROTOCOL:http}
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${eureka.instance.http-protocol}://${eureka.instance.hostname}:${eureka.instance.port}/eureka/ 
