spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ems_system
    username: root
    password: root
    driver-class-name: "com.mysql.jdbc.Driver"
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: validate
server:
  port: ${PORT:0}